# Generated by Django 4.2.4 on 2023-08-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stduent',
            new_name='Student',
        ),
    ]
